<template>
  <div class="flex flex-row flex-wrap gap-1 md:gap-3 p-1">
    <div class="flex h-5">
      <img
        width="20"
        height="20"
        class="h-5"
        src="~/assets/baseline/chrome.svg"
        alt=""
      />
      <img
        width="20"
        height="20"
        class="h-5"
        src="~/assets/baseline/browser-check.svg"
        alt=""
      />
    </div>
    <div class="flex h-5">
      <img
        width="20"
        height="20"
        class="h-5"
        src="~/assets/baseline/edge.svg"
        alt=""
      />
      <img
        width="20"
        height="20"
        class="h-5"
        src="~/assets/baseline/browser-check.svg"
        alt=""
      />
    </div>
    <div class="flex h-5">
      <img
        width="20"
        height="20"
        class="h-5"
        src="~/assets/baseline/firefox.svg"
        alt=""
      />
      <img
        width="20"
        height="20"
        class="h-5"
        src="~/assets/baseline/browser-check.svg"
        alt=""
      />
    </div>
    <div class="flex h-5">
      <img
        width="20"
        height="20"
        class="h-5"
        src="~/assets/baseline/safari.svg"
        alt=""
      />
      <img
        width="20"
        height="20"
        class="h-5"
        src="~/assets/baseline/browser-check.svg"
        alt=""
      />
    </div>
  </div>
</template>
